name: axiom
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3.11
  - xarray>=2023.5.0
  - netcdf4>=1.6.3
  - h5netcdf>=1.1.0
  - cerberus>=1.3.4
  - tabulate>=0.9.0
  - dask>=2023.5.1
  - distributed>=2023.5.1
  - tqdm>=4.65.0
  - jinja2>=3.1.2
  - importlib-metadata>=6.6.0
  - pip:
    - blush>=1.1.2